name: python

on: push

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Test env vars for python
      run: ENV_SECRET=${{ secrets.ENV_SECRET }} REPO_SECRET=${{ secrets.REPO_SECRET }} python -c 'import os;print(os.environ)'


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install poetry
      uses: snok/install-poetry@v1.1.2
      with:
          virtualenvs-create: true
          virtualenvs-in-project: true

    - name: Cache poetry venv
      uses: actions/cache@v2
      id: poetry-cache
      with:
        path: ~/.poetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Dependencies
      if: steps.poetry-cache.outputs.cache-hit != 'true'
      run: poetry install -vv

    - name: Show poetry env info
      run: |
        poetry env info
        poetry config --list

    - name: Test poetry run
      run: |
        poetry run pip list
